name: Extension tutorial request
description: Use this form to propose new Chrome Extension tutorial
title: "[EXT-TUTORIAL] <title>"
labels: [content, extensions]
assignees: AmySteam
body:
- type: markdown
  attributes:
    value: "## Thank you for requesting a new Chrome Extension tutorial, please fill out this form!"
- type: textarea
  attributes:
    label: What would this extension do?
    description: A concise description of how the extension would work.
  validations:
    required: true
- type: textarea
  attributes:
    label: What lessons would this tutorial teach?
    description: Top three lessons of what extension concepts it will cover.
    placeholder: |
      1. ...
      2. ...
      3. ...    
  validations:
    required: true
- type: textarea
  attributes:
    label: What Chrome APIs would be featured?
    description: Top three Chrome APIs you'd like to see demonstrated.
    placeholder: |
      1. ...
      2. ...
      3. ...
  validations:
    required: true
- type: dropdown
  attributes:
    label: Extension components
    description: Is there a specific component you would like to see?
    multiple: true
    options:
      - label: Service worker
      - label: Popup
      - label: Overlay (content script)
      - label: Omnibox
      - label: Context Menu
      - label: Options page
      - label: Doesn't matter
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the tutorial you are requesting!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: "Thanks again for sharing your extension tutorial ideas with us!" 
